/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "createEscrow" | "dispute" | "escrows" | "fund" | "nextEscrowId" | "refund" | "release" | "reputationRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowCreated" | "EscrowDisputed" | "EscrowFunded" | "EscrowRefunded" | "EscrowReleased"): EventFragment;

    encodeFunctionData(functionFragment: 'createEscrow', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'dispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextEscrowId', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'release', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEscrowId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
  }

  
    export namespace EscrowCreatedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, payee: AddressLike, arbiter: AddressLike, deadline: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payer: string, payee: string, arbiter: string, deadline: bigint];
      export interface OutputObject {escrowId: bigint, payer: string, payee: string, arbiter: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowDisputedEvent {
      export type InputTuple = [escrowId: BigNumberish, disputer: AddressLike];
      export type OutputTuple = [escrowId: bigint, disputer: string];
      export interface OutputObject {escrowId: bigint, disputer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payer: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, payer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowRefundedEvent {
      export type InputTuple = [escrowId: BigNumberish, payer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payer: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, payer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [escrowId: BigNumberish, payee: AddressLike, amount: BigNumberish];
      export type OutputTuple = [escrowId: bigint, payee: string, amount: bigint];
      export interface OutputObject {escrowId: bigint, payee: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createEscrow: TypedContractMethod<
      [payee: AddressLike, arbiter: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    dispute: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {payer: string, payee: string, arbiter: string, amount: bigint, deadline: bigint, state: bigint }],
      'view'
    >
    

    
    fund: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    nextEscrowId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    release: TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [payee: AddressLike, arbiter: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'dispute'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint] & {payer: string, payee: string, arbiter: string, amount: bigint, deadline: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'fund'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'nextEscrowId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [escrowId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowDisputed'): TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'EscrowRefunded'): TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;

    filters: {
      
      'EscrowCreated(uint256,address,address,address,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowDisputed(uint256,address)': TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
      EscrowDisputed: TypedContractEvent<EscrowDisputedEvent.InputTuple, EscrowDisputedEvent.OutputTuple, EscrowDisputedEvent.OutputObject>;
    

      'EscrowFunded(uint256,address,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'EscrowRefunded(uint256,address,uint256)': TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
      EscrowRefunded: TypedContractEvent<EscrowRefundedEvent.InputTuple, EscrowRefundedEvent.OutputTuple, EscrowRefundedEvent.OutputObject>;
    

      'EscrowReleased(uint256,address,uint256)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    
    };
  }