/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ReputationRegistryInterface extends Interface {
    getFunction(nameOrSignature: "escrowContract" | "leaderboard" | "owner" | "participantCount" | "participants" | "recordSettlement" | "reputationOf" | "setEscrowContract"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EscrowContractSet" | "SettlementRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'escrowContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'leaderboard', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'participantCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'participants', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordSettlement', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputationOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setEscrowContract', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'escrowContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leaderboard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participantCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrowContract', data: BytesLike): Result;
  }

  
    export namespace EscrowContractSetEvent {
      export type InputTuple = [escrowContract: AddressLike];
      export type OutputTuple = [escrowContract: string];
      export interface OutputObject {escrowContract: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettlementRecordedEvent {
      export type InputTuple = [payer: AddressLike, payee: AddressLike, amount: BigNumberish, payerCount: BigNumberish, payeeCount: BigNumberish];
      export type OutputTuple = [payer: string, payee: string, amount: bigint, payerCount: bigint, payeeCount: bigint];
      export interface OutputObject {payer: string, payee: string, amount: bigint, payerCount: bigint, payeeCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReputationRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReputationRegistry;
    waitForDeployment(): Promise<this>;

    interface: ReputationRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    escrowContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    leaderboard: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint[], bigint[]] & {addrs: string[], counts: bigint[], volumes: bigint[] }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    participantCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    participants: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    recordSettlement: TypedContractMethod<
      [payer: AddressLike, payee: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputationOf: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint] & {count: bigint, volume: bigint }],
      'view'
    >
    

    
    setEscrowContract: TypedContractMethod<
      [_escrowContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'escrowContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'leaderboard'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint[], bigint[]] & {addrs: string[], counts: bigint[], volumes: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'participantCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'participants'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordSettlement'): TypedContractMethod<
      [payer: AddressLike, payee: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputationOf'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint] & {count: bigint, volume: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setEscrowContract'): TypedContractMethod<
      [_escrowContract: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EscrowContractSet'): TypedContractEvent<EscrowContractSetEvent.InputTuple, EscrowContractSetEvent.OutputTuple, EscrowContractSetEvent.OutputObject>;
getEvent(key: 'SettlementRecorded'): TypedContractEvent<SettlementRecordedEvent.InputTuple, SettlementRecordedEvent.OutputTuple, SettlementRecordedEvent.OutputObject>;

    filters: {
      
      'EscrowContractSet(address)': TypedContractEvent<EscrowContractSetEvent.InputTuple, EscrowContractSetEvent.OutputTuple, EscrowContractSetEvent.OutputObject>;
      EscrowContractSet: TypedContractEvent<EscrowContractSetEvent.InputTuple, EscrowContractSetEvent.OutputTuple, EscrowContractSetEvent.OutputObject>;
    

      'SettlementRecorded(address,address,uint256,uint256,uint256)': TypedContractEvent<SettlementRecordedEvent.InputTuple, SettlementRecordedEvent.OutputTuple, SettlementRecordedEvent.OutputObject>;
      SettlementRecorded: TypedContractEvent<SettlementRecordedEvent.InputTuple, SettlementRecordedEvent.OutputTuple, SettlementRecordedEvent.OutputObject>;
    
    };
  }